{{ config(
    materialized='table',
    unique_key='employee_id',
) }}


with raw as (
    select
        {% if target.name == 'duckdb_dev' %}
            TRY_CAST(employee_number AS BIGINT) as employee_id,
            TRY_CAST(first_name AS STRING) as first_name,
            TRY_CAST(last_name AS STRING) as last_name,
            TRY_CAST(middle_name AS STRING) as middle_name,
            TRY_CAST(preferred_name AS STRING) as preferred_name,
            TRY_CAST(gender AS STRING) as gender,
            TRY_CAST(age AS BIGINT) as age,
            CAST(try_strptime(date_of_birth, '%Y-%m-%d') AS DATE) as date_of_birth,
            TRY_CAST(marital_status AS STRING) as marital_status,
            TRY_CAST(email AS STRING) as email,
            TRY_CAST(home_email AS STRING) as home_email,
            TRY_CAST(work_phone AS STRING) as work_phone,
            TRY_CAST(work_phone_ext AS STRING) as work_phone_ext,
            TRY_CAST(mobile_phone AS STRING) as mobile_phone,
            TRY_CAST(home_phone AS STRING) as home_phone,
            TRY_CAST(address_line_one AS STRING) as address_line_one,
            TRY_CAST(address_line_two AS STRING) as address_line_two,
            TRY_CAST(city AS STRING) as city,
            TRY_CAST(state AS STRING) as state,
            TRY_CAST(zipcode AS STRING) as zipcode,
            TRY_CAST(country AS STRING) as country,
            TRY_CAST(employment_status AS STRING) as employment_status,
            CAST(try_strptime(hire_date, '%Y-%m-%d') AS DATE) as hire_date,
            CAST(try_strptime(original_hire_date, '%Y-%m-%d') AS DATE) as original_hire_date,
            CAST(try_strptime(termination_date, '%Y-%m-%d') AS DATE) as termination_date,
            TRY_CAST(job_information_department AS STRING) as department,
            TRY_CAST(job_information_division AS STRING) as division,
            TRY_CAST(job_information_job_title AS STRING) as job_title,
            TRY_CAST(job_information_location AS STRING) as location,
            TRY_CAST(job_information_reports_to AS STRING) as reports_to,
            TRY_CAST(compensation_change_reason AS STRING) as compensation_change_reason,
            CAST(try_strptime(compensation_effective_date, '%Y-%m-%d') AS DATE) as compensation_effective_date,
            TRY_CAST(regexp_replace(compensation_pay_rate, '[^0-9.]', '') AS DOUBLE) as pay_rate,
            TRY_CAST(compensation_pay_type AS STRING) as pay_type,
            TRY_CAST(compensation_pay_schedule AS STRING) as pay_schedule,
            TRY_CAST(compensation_overtime_status AS STRING) as overtime_status,
            TRY_CAST(custom_field4460 AS STRING) as seid,
            TRY_CAST(custom_field4472 AS BIGINT) as total_years_edu_service,
            TRY_CAST(custom_field4473 AS BIGINT) as total_years_in_lea,
            TRY_CAST(custom_field4554 AS BIGINT) as years_of_experience,
            (custom_field4475 = 'Yes') as is_hispanic,
            TRY_CAST(custom_field4476 AS STRING) as ethnicity_and_race,
            TRY_CAST(custom_field4477 AS STRING) as school,
            TRY_CAST(custom_field4505 AS DOUBLE) as fte,
            TRY_CAST(custom_field4506 AS STRING) as highest_education,
            TRY_CAST(custom_field4507 AS STRING) as job_classification_code,
            TRY_CAST(custom_field4508 AS STRING) as status_of_employment,
            TRY_CAST(custom_field4597 AS STRING) as prior_last_name,
            TRY_CAST(education_college_or_institution AS STRING) as college,
            TRY_CAST(education_degree AS STRING) as degree,
            CAST(try_strptime(education_start_date, '%Y-%m-%d') AS DATE) as education_start_date,
            CAST(try_strptime(education_end_date, '%Y-%m-%d') AS DATE) as education_end_date,
            TRY_CAST(education_major_or_specialization AS STRING) as major,
            TRY_CAST(education_gpa AS DOUBLE) as gpa,
            CAST(try_strptime(custom_table4463, '%Y-%m-%d') AS DATE) as credential_effective_date,
            CAST(try_strptime(custom_table4464, '%Y-%m-%d') AS DATE) as credential_expiration_date,
            CAST(try_strptime(custom_table4465, '%Y-%m-%d') AS DATE) as credential_renewal_date,
            TRY_CAST(custom_table4466 AS STRING) as credential_comments,
            TRY_CAST(custom_table4487 AS STRING) as credential_title,
            TRY_CAST(custom_table4556 AS STRING) as credential_document_type,
            TRY_CAST(custom_table4557 AS STRING) as credential_document_number,
            TRY_CAST(custom_table4558 AS STRING) as credential_additional_auth,
            TRY_CAST(custom_table4559 AS STRING) as credential_term,
            TRY_CAST(custom_table4560 AS STRING) as credential_subject,
            TRY_CAST(custom_table4590 AS STRING) as credential_status,
            last_changed as last_changed,
            last_changed_iso as last_changed_iso,
            TRY_CAST(created_by_user_id AS STRING) as created_by_user_id,
            _dlt_load_id,
            _dlt_id
        {% else %}
            SAFE_CAST(employee_number as INT64) as employee_id,
            SAFE_CAST(first_name as STRING) as first_name,
            SAFE_CAST(last_name as STRING) as last_name,
            SAFE_CAST(middle_name as STRING) as middle_name,
            SAFE_CAST(preferred_name as STRING) as preferred_name,
            SAFE_CAST(gender as STRING) as gender,
            SAFE_CAST(age as INT64) as age,
            SAFE.PARSE_DATE('%Y-%m-%d', date_of_birth) as date_of_birth,
            SAFE_CAST(marital_status as STRING) as marital_status,
            SAFE_CAST(email as STRING) as email,
            SAFE_CAST(home_email as STRING) as home_email,
            SAFE_CAST(work_phone as STRING) as work_phone,
            SAFE_CAST(work_phone_ext as STRING) as work_phone_ext,
            SAFE_CAST(mobile_phone as STRING) as mobile_phone,
            SAFE_CAST(home_phone as STRING) as home_phone,
            SAFE_CAST(address_line_one as STRING) as address_line_one,
            SAFE_CAST(address_line_two as STRING) as address_line_two,
            SAFE_CAST(city as STRING) as city,
            SAFE_CAST(state as STRING) as state,
            SAFE_CAST(zipcode as STRING) as zipcode,
            SAFE_CAST(country as STRING) as country,
            SAFE_CAST(employment_status as STRING) as employment_status,
            SAFE.PARSE_DATE('%Y-%m-%d', hire_date) as hire_date,
            SAFE.PARSE_DATE('%Y-%m-%d', original_hire_date) as original_hire_date,
            SAFE.PARSE_DATE('%Y-%m-%d', termination_date) as termination_date,
            SAFE_CAST(job_information_department as STRING) as department,
            SAFE_CAST(job_information_division as STRING) as division,
            SAFE_CAST(job_information_job_title as STRING) as job_title,
            SAFE_CAST(job_information_location as STRING) as location,
            SAFE_CAST(job_information_reports_to as STRING) as reports_to,
            SAFE_CAST(compensation_change_reason as STRING) as compensation_change_reason,
            SAFE.PARSE_DATE('%Y-%m-%d', compensation_effective_date) as compensation_effective_date,
            SAFE_CAST(regexp_replace(compensation_pay_rate, r'[^0-9.]', '') as DECIMAL) as pay_rate,
            SAFE_CAST(compensation_pay_type as STRING) as pay_type,
            SAFE_CAST(compensation_pay_schedule as STRING) as pay_schedule,
            SAFE_CAST(compensation_overtime_status as STRING) as overtime_status,
            SAFE_CAST(custom_field4460 as STRING) as seid,
            SAFE_CAST(custom_field4472 as INT64) as total_years_edu_service,
            SAFE_CAST(custom_field4473 as INT64) as total_years_in_lea,
            SAFE_CAST(custom_field4554 as INT64) as years_of_experience,
            (custom_field4475 = 'Yes') as is_hispanic,
            SAFE_CAST(custom_field4476 as STRING) as ethnicity_and_race,
            SAFE_CAST(custom_field4477 as STRING) as school,
            SAFE_CAST(custom_field4505 as DECIMAL) as fte,
            SAFE_CAST(custom_field4506 as STRING) as highest_education,
            SAFE_CAST(custom_field4507 as STRING) as job_classification_code,
            SAFE_CAST(custom_field4508 as STRING) as status_of_employment,
            SAFE_CAST(custom_field4597 as STRING) as prior_last_name,
            SAFE_CAST(education_college_or_institution as STRING) as college,
            SAFE_CAST(education_degree as STRING) as degree,
            SAFE.PARSE_DATE('%Y-%m-%d', education_start_date) as education_start_date,
            SAFE.PARSE_DATE('%Y-%m-%d', education_end_date) as education_end_date,
            SAFE_CAST(education_major_or_specialization as STRING) as major,
            SAFE_CAST(education_gpa as DECIMAL) as gpa,
            SAFE.PARSE_DATE('%Y-%m-%d', custom_table4463) as credential_effective_date,
            SAFE.PARSE_DATE('%Y-%m-%d', custom_table4464) as credential_expiration_date,
            SAFE.PARSE_DATE('%Y-%m-%d', custom_table4465) as credential_renewal_date,
            SAFE_CAST(custom_table4466 as STRING) as credential_comments,
            SAFE_CAST(custom_table4487 as STRING) as credential_title,
            SAFE_CAST(custom_table4556 as STRING) as credential_document_type,
            SAFE_CAST(custom_table4557 as STRING) as credential_document_number,
            SAFE_CAST(custom_table4558 as STRING) as credential_additional_auth,
            SAFE_CAST(custom_table4559 as STRING) as credential_term,
            SAFE_CAST(custom_table4560 as STRING) as credential_subject,
            SAFE_CAST(custom_table4590 as STRING) as credential_status,
            last_changed as last_changed,
            last_changed_iso as last_changed_iso,
            SAFE_CAST(created_by_user_id as STRING) as created_by_user_id,
            _dlt_load_id,
            _dlt_id
        {% endif %}
    from {{ source('raw_staff_data', 'raw_bamboohr') }}
    {% if is_incremental() %}
      where _dlt_load_id > (select max(_dlt_load_id) from {{ this }})
    {% endif %}
)

select *
from raw
