# Read pre-commit hook framework https://pre-commit.com/ for more details about the structure of config yaml file and how git pre-commit would invoke each hook.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: detect-private-key
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      args: [--baseline, .secrets.baseline]
# terraform hooks
# - repo: https://github.com/gruntwork-io/pre-commit
#   rev: v0.1.17
#   hooks:
#     - id: terraform-fmt
#     - id: terraform-validate
#     - id: tflint
#       args:
#         - "--module"
#         - "--config=.tflint.hcl"
# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: v1.77.0
#   hooks:
#       - id: terraform_tfsec
# packer hooks
# - repo: https://github.com/cisagov/pre-commit-packer
#   rev: v0.0.2
#   hooks:
#     - id: packer_fmt
#     - id: packer_validate
# remove carriage return line feed
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
    - id: remove-crlf
