default:
  outputs:
    staff:
      type: bigquery
      method: service-account
      project: calibrate-data
      dataset: staff
      threads: 4
      keyfile: '../../.secrets/gcp_bigquery.json'
    duckdb_dev:
      type: duckdb
      path: '../../../data/duckdb/dev.duckdb'
      threads: 4
  target: 'staff'
