default:
  outputs:
    staff:
      dataset: staff
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: '../../../.secrets/gcp_bigquery.json' # Corrected path
      location: US
      method: service-account-json
      priority: interactive
      project: '{{ env_var(''GCP_PROJECT'') }}'
      threads: 4
      type: bigquery
  target: 'staff'
